### ISSUE TITLE
Regex is not working for find

### ISSUE THREAD

**Issue by TeKett** [Nenotriple/img-txt_viewer#27] opened 2024-08-11 15:43 UTC
No matter what regex i enter its not working. To be specific of what i trying to find is "any text but no text if word1 or word2 exists". Which looks like this `^(?!.*\b(?:word1|word2)\b).*`, but a simple `word1|word2` does not work either and gives no results.

**Comment by Nenotriple** [comment] 2024-08-11 20:53
I must not have fully set that up and then I moved onto something else because the Regex check button/toggle doesn't really do anything in the scope of filtering. I'll get this working as intended soon, but in the meantime you can still filter in the way you described.

Starting a "line" with an exclamation mark ! will exclude that text from the filter. You can also join multiple lines together with a + character. Like this: "!word1 + !word2" (there must be a space before and after the +), this will exclude any text files containing word1 or word2.

**Comment by Nenotriple** [comment] 2024-08-20 07:43
This issue is fixed in v1.95 952ee74

**Closed by Nenotriple** 2024-08-20 07:43 UTC
